table=[
"48 48 3 1 ",
"  c None",
". c #2F2F2F",
"X c gray19",
"        ..                                      ",
"       X.XX                                     ",
"       ....      .............                  ",
"      XX.XXX  .XX.XX.XX.XX.XX.XXX               ",
"      XX.XXX.X.XX.XX.XX.XX.XX.XXX.X             ",
"      ...............................           ",
"     .XX.XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX         ",
"     .XX.XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.        ",
"    .....................................       ",
"    X.XX.XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.XX      ",
"    X.XX.XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.XX.     ",
"   .........................................    ",
"   XX.XX.XXX.X.XX.XX.XX.XX.XX.X       X.XX.XX   ",
"   XX.XX.XXX.X.XX.XX.XX.XX.               .XX.  ",
"  ......................                    ... ",
"  .XX.XX.XXX.X.XX.XX.X                        X.",
" X.XX.XX.XXX.X.XX.XX                            ",
" X.XX.XX.XXX.X.XX.XX                            ",
"  ..................                            ",
"   XX.XX.XXX.X.XX.XX.                           ",
"      XX.XXX.X.XX.XX.X                          ",
"            ..........                          ",
"                  XX.                           ",
"                                                ",
"                                                ",
"                           XX.                  ",
"                          .XX.XXX.XX            ",
"                          ................      ",
"                           XX.XXX.XX.XX.XX.XX   ",
"                            X.XXX.XX.XX.XX.XX.  ",
"                            ................... ",
"                            X.XXX.XX.XX.XX.XX.X ",
"XX                        .XX.XXX.XX.XX.XX.XX.  ",
" ...                    ......................  ",
"  .XX.               XX.XX.XX.XXX.XX.XX.XX.XX   ",
"   .......       ............................   ",
"    X.XX.XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.XX.XX   ",
"     .XX.XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.XX.X    ",
"      XX.XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.XX.X    ",
"       .....................................    ",
"        .XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.XX.     ",
"         XXX.X.XX.XX.XX.XX.XX.XXX.XX.XX.XX.     ",
"           ...............................      ",
"             X.XX.XX.XX.XX.XX.XXX.XX.XX.XX      ",
"               XX.XX.XX.XX.XX.XXX.  .XX.XX      ",
"                  .............      ....       ",
"                                     XX.X       ",
"                                      X.        "
]